# fly.toml app configuration file generated for daily-trends-go on 2024-11-17T15:21:49+01:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'daily-trends-go'
primary_region = 'mad'

[build]
  [build.args]
    GO_VERSION = '1.22.5'

[env]
  PORT = '8080'

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
